title: Nassets                 # title of the site
description: Nassets           # description of the site
url: https://nassets.github.io # domain
baseurl: ""                    # root directory

# Path of site resources
img: assets/img
css: assets/css

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# default layout of the articles in _posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

        # disqus: nassets
email: nanjisheng@yandex.com

socials:
- name: github
  url: https://github.com/nassetsg
- name: twitter
  url: https://ttti.cc


nav:
- name: Home
  path: /
- name: Project
  path: /pages/project.html
- name: About
  path: /pages/about.html
